### ISSUE TITLE
Inject Nestjs providers into consumer

### ISSUE THREAD

**Issue by Greibit** [rob3000/nestjs-kafka#25]
Hi, 

I'm trying to inject a class into my Kafka Consumer but i can't:

```typescript
import { Inject } from '@nestjs/common';
import { KafkaService, SubscribeTo } from '@rob3000/nestjs-kafka';
import { TestService } from '../../application/test.service';

export class TestConsumer {
  constructor(
      @Inject('TEST_KAFKA') private client: KafkaService,
      @Inject('TestService') private testService: TestService
  ) {
  }

  onModuleInit(): void {
    this.client.subscribeToResponseOf('item.created', this.client);
  }

  @SubscribeTo('item.created')
  async itemCreated(data): Promise<void> {

    await this.testService.createItem(data.id, data.companyId);
  }
}
```

The error I'm getting is 

```Cannot read property 'createItem' of undefined. ```

The service testService is undefined when the method createItem is called, I think this is because the KafkaClient is executing the "createItem" method as a callback instead of using the TestConsumer class.
I used the "TestService" dependency in other parts of the app so it's not a configuration or definition problem.

How can I inject or use dependencies in my Kafka consumers?

Thanks!

**Comment by rob3000** [comment]
Hi @Greibit I notice you have the following:

```
onModuleInit(): void {
    this.client.subscribeToResponseOf('item.created', this.client);
  }
```

I ideally you just need to pass `this` for example:
```
onModuleInit(): void {
    this.client.subscribeToResponseOf('item.created', this);
  }
```
This will then pass the instance back when your method is called.

**Comment by Greibit** [comment]
Hi @rob3000, thats was the problem.

Thank you so much!
