### ISSUE TITLE
Avro deserializer fails if key is not avro format

### ISSUE THREAD

**Issue by ColinMorris83** [rob3000/nestjs-kafka#29]
Can an option be added to not call decode on message keys, in our case only message values need decoding, and therefore we can't use the built in avro deserialiser class.

Also perhaps the use of a deserialiser can be documented to mention that you must return the message with a response property on it because of this line: 

const { timestamp, response, offset, key } = await this.deserializer.deserialize(message, { topic });

As it seems that it's this response property that will be the data in any methods that are decorated with SubscribeTo.

**Comment by agboon** [comment]
Agree with this issue, made a PR fixing this: https://github.com/rob3000/nestjs-kafka/pull/31
@rob3000 pls review.

**Comment by rob3000** [comment]
Thanks @r45boon Just merged this PR

**Comment by agboon** [comment]
@rob3000 i have a quickfix to this, pls merge https://github.com/rob3000/nestjs-kafka/pull/34
