### ISSUE TITLE
Support for commitOffsets on npm

### ISSUE THREAD

**Issue by matcampos** [rob3000/nestjs-kafka#36]
I noticed that the version published on npm is quite outdated compared to the version that is here on github, I would really like to use your library but I need the commitOffsets method where it invokes the commitOffsets method of the consumer's private instance, do you anticipate when this will be available on npm?

**Comment by rob3000** [comment]
Hi @matcampos just published ver 1.5 to npm!

**Comment by matcampos** [comment]
Thank you so much!! @rob3000  :)
