### ISSUE TITLE
nestjs microservice kafka

### ISSUE THREAD

**Issue by kodeine** [rob3000/nestjs-kafka#4]
Hello,

I like your library but i wanted to know how it is different from nestjs microservice kafka transport?

**Comment by rob3000** [comment]
Hi @kodeine, 

The main difference is that the [nestjs microservice transport](https://docs.nestjs.com/microservices/kafka#message-pattern) uses a [request reply channel pattern](https://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html) for communication, where as this library allows your to subscribe to any topic and produce to any topic. This then allows you to build microservices that could transform that data and push to a new topic for example. This library also support Avro message encoding and decoding.

Hope that answers your question?

**Comment by kodeine** [comment]
@rob3000 yep it answers my question, looks like i'll migrate to this lib.
Also, does this library validate the dto's? nestjs version doesnt validate the dto's

**Comment by rob3000** [comment]
Hey @kodeine not sure i understand what you mean by the dto's?

**Comment by kodeine** [comment]
input validation using `class-validator`. like i would want the inputs validated when payload is received.

```
import { IsNumber, IsString } from 'class-validator';

export class SomeDto {
  @Expose()
  @IsNumber()
  readonly id!: number;

  @Expose()
  @IsString()
  readonly something!: string[];
}


@MessagePattern('account_me')
  getMe(
    @Payload() payload: SomeDto,
  ) {
      console.log('Received payload', payload);
  }

```

**Comment by rob3000** [comment]
Ah! So it kind of does that if you are using the Avro Serialiser as when a message is received it will decode it against the registered schema from schema registry. You'd defined your schema such as:

```
{
  "type": "record",
  "name": "value",
  "namespace": "account_me",
  "doc": "",
  "fields": [
    {
      "name": "id",
      "type": "number",
      "doc": "An id."
    },
    {
      "name": "something",
      "doc": "an array of strings",
      "type": { 
        "type": "array",
        "items": "string"
      } 
    }
 ]
}
```
Upload it to schema registry and then you could convert the avro schema into types and then use that as validation. Hope that helps.

**Comment by kodeine** [comment]
okay let me research more on registry schema, im new to kafka so trying to absorb its knowledge. 
one last question, i dont need to use nestjs microservice for kafka if im using your library right?

**Comment by rob3000** [comment]
A good article on schema registry is: https://docs.confluent.io/platform/current/schema-registry/index.html

It does have a dependency on [nestjs/microservice](https://github.com/rob3000/nestjs-kafka/blob/master/package.json#L36) as we do use some of the types:
* https://github.com/rob3000/nestjs-kafka/blob/master/src/deserializer/kafka-response.deserializer.ts#L1
* https://github.com/rob3000/nestjs-kafka/blob/master/src/serializer/kafka-request.serializer.ts#L8

If you were just looking to create a Kafka consumer/producer with node take a look at [KafkaJS](https://kafka.js.org/) which is the library [we use for the service](https://github.com/rob3000/nestjs-kafka/blob/master/src/kafka.service.ts#L2). Basically this library integrates [KafkaJS](https://kafka.js.org/)  and [Schema registry](https://github.com/kafkajs/confluent-schema-registry) for use with NestJS.

**Comment by kodeine** [comment]
awesome and thank you for quick responses really appreciate your help. 
I'll review the links and will come to you if any questions.

**Comment by rob3000** [comment]
No Problems. I'll close this issue off, but feel free to reach out if you have any issues.

**Comment by kodeine** [comment]
So I have a question, how do we handle errors?
For example, if we throw an exception to consumer side. How can we catch that error and display on api endpoint side? 

So this is the flow (I think)

Http post, /users/, verify input at http api level.
 Pass request to microservice.
Kafka receives the user obj as payload. 
If something item is missing, we throw exception, now how that exception would go back as an error to be displayed?
