### ISSUE TITLE
Connection error: connect EACCES 

### ISSUE THREAD

**Issue by wishygupta** [rob3000/nestjs-kafka#46]
`{"level":"ERROR","timestamp":"2022-07-19T09:52:20.557Z","logger":"kafkajs","message":"[Connection] Connection error: connect EACCES fe80::b03d:38e1:27b3:9e22:9092","broker":"W10-lTkFoL0JX1t.radisys.com:9092","clientId":"ScannerService","stack":"Error: connect EACCES fe80::b03d:38e1:27b3:9e22:9092\n    at 
TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)"}
{"level":"ERROR","timestamp":"2022-07-19T09:52:20.561Z","logger":"kafkajs","message":"[Connection] Connection error: connect EACCES fe80::b03d:38e1:27b3:9e22:9092","broker":"W10-lTkFoL0JX1t.radisys.com:9092","clientId":"ScannerService","stack":"Error: connect EACCES fe80::b03d:38e1:27b3:9e22:9092\n    at 
TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)"}`

I am not able to understand what is the issue over here?
I am running kafka on local machine with `KAFKA_BROKERS="127.0.0.1:9092"`

**Comment by rob3000** [comment]
Hey @wishygupta if you're running Kafka on a local machine where does 'W10-lTkFoL0JX1t.radisys.com:9092' get set? This should be replaced with your localhost broker e.g `127.0.0.1:9092`

**Comment by wishygupta** [comment]
@rob3000  I am not sure from where this gets set `W10-lTkFoL0JX1t.radisys.com:9092`. Since in the JS code I am specifically assigning the localhost `127.0.0.1:9092`. Even in the kafka server properties it is not defined. Seems somehow it is triggering that

**Comment by rob3000** [comment]
@wishygupta are you able to paste in your config on how you're defining it?

**Comment by wishygupta** [comment]
@rob3000 
This is the kafka server properties files

`broker.id=0

num.network.threads=3

num.io.threads=8

socket.send.buffer.bytes=102400

socket.receive.buffer.bytes=102400

socket.request.max.bytes=104857600

log.dirs=C:/Users/wgupta/Backend/kafka/kafka-logs

num.partitions=1

num.recovery.threads.per.data.dir=1

offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

log.retention.hours=168

log.segment.bytes=1073741824

log.retention.check.interval.ms=300000

zookeeper.connect=localhost:2181

zookeeper.connection.timeout.ms=18000

group.initial.rebalance.delay.ms=0`
